"""added language field to post model

Revision ID: 627d1abcf337
Revises: d57ca4ca6f2c
Create Date: 2018-12-26 16:23:39.159476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627d1abcf337'
down_revision = 'd57ca4ca6f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
